### ISSUE TITLE
Hastic standalone docker and influx, analytic status: Network Error

### ISSUE THREAD

**Issue by maxdd** [hastic/hastic#110]
Hello,
i was trying to play a bit with this tool but i get the following

![image](https://user-images.githubusercontent.com/6155973/190450628-9ac70d01-1dfb-4b4e-ae62-9b99ac2b53d3.png)

Description:
The error above was given by Adblock extension but in any case i cant "connect" the influx database to hastic (see below)

Setup:
Influxdb and grafana are on the same docker-compose file of hastic and both are under authentication.
Influxdb and grafana are running ok and i can plot all my data.
Sensors are posting to influx with the same token i'm using for hastic

Regards,

**Comment by maxdd** [comment]
OK so the Adblock plugin was blocking the loading of the page which is quite strange

**Comment by maxdd** [comment]
I also added org and token for completeness but still the same issue:

      HASTIC_INFLUX__ORG_ID: "****"
      HASTIC_INFLUX__TOKEN: "****"

 but


          port => 4347
          influx.url => http://192.168.1.52:8086
          influx.org-id => ****
          influx.token => ****
          influx.query => from(bucket: "eMgr")
            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
            |> filter(fn: (r) => r["_measurement"] == "sdm230")
            |> filter(fn: (r) => r["_field"] == "L1_P")
          Start server on 4347 port
          Detection runner started from 1663320478
          thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error trying to connect: tcp connect error: Connection refused (os error 111)
          Caused by:
              0: tcp connect error: Connection refused (os error 111)
              1: Connection refused (os error 111)', src/services/analytic_service/analytic_unit/threshold_analytic_unit.rs:53:59
          stack backtrace:
             0:     0x7f4111791dac - std::backtrace_rs::backtrace::libunwind::trace::hc1bc96ddb4426aa4
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
             1:     0x7f4111791dac - std::backtrace_rs::backtrace::trace_unsynchronized::h923980a653d66493
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
             2:     0x7f4111791dac - std::sys_common::backtrace::_print_fmt::h9c757c85a437b931
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
             3:     0x7f4111791dac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4daee6a3bf7c86e
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
             4:     0x7f41117cf5fc - core::fmt::write::hb92fcd00ba9c1ad2
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
             5:     0x7f411178b715 - std::io::Write::write_fmt::he1040163a0175759
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
             6:     0x7f4111793930 - std::sys_common::backtrace::_print::h41aed1f85e85fe81
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
             7:     0x7f4111793930 - std::sys_common::backtrace::print::h80502ae1de52b70b
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
             8:     0x7f4111793930 - std::panicking::default_hook::{{closure}}::ha8bcafa5b9176f3f
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
             9:     0x7f41117934e5 - std::panicking::default_hook::hfaee58ed0a065bec
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
            10:     0x7f4111793fe4 - std::panicking::rust_panic_with_hook::h8ce3328d937db5aa
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
            11:     0x7f4111793ac0 - std::panicking::begin_panic_handler::{{closure}}::h1f2295b855ba5030
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
            12:     0x7f4111792254 - std::sys_common::backtrace::__rust_end_short_backtrace::h17092a58b60b0566
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
            13:     0x7f4111793a29 - rust_begin_unwind
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
            14:     0x7f4111285581 - core::panicking::panic_fmt::hcf6bd03e382adeab
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
            15:     0x7f4111285673 - core::result::unwrap_failed::h831f708977462148
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
            16:     0x7f41113bf5f4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h03175601afbd239d
            17:     0x7f41113c4940 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha460b1312f43ab48
            18:     0x7f4111391e5a - tokio::runtime::task::core::CoreStage<T>::poll::h57db0178c8d44e0b
            19:     0x7f41113b9c26 - tokio::runtime::task::harness::Harness<T,S>::poll::h9252b4edaf03db37
            20:     0x7f4111756166 - tokio::runtime::thread_pool::worker::Context::run_task::h5d7bd1542cd0cc1c
            21:     0x7f4111755678 - tokio::runtime::thread_pool::worker::Context::run::he36b467483250087
            22:     0x7f4111741ae5 - tokio::macros::scoped_tls::ScopedKey<T>::set::h693fb30e4d8d070d
            23:     0x7f4111754abc - tokio::runtime::thread_pool::worker::run::hf93f530505a6e5b9
            24:     0x7f411175905f - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h278f839eccb43237
            25:     0x7f411174e658 - tokio::runtime::task::harness::Harness<T,S>::poll::hc241429d81860416
            26:     0x7f411174cf46 - tokio::runtime::blocking::pool::Inner::run::he022b7af820552a4
            27:     0x7f41117401fa - std::sys_common::backtrace::__rust_begin_short_backtrace::h5048c5b1ceb9851a
            28:     0x7f4111758838 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he441f9d931d9a7d8
            29:     0x7f4111796ee3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h397d68d70ff528a2
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
            30:     0x7f4111796ee3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd5553548a13795d4
                                         at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
            31:     0x7f4111796ee3 - std::sys::unix::thread::Thread::new::thread_start::h0d91a24d2432f091

**Comment by maxdd** [comment]
From inside the docker

          root@ubuntu:/# ping 192.168.1.52
          PING 192.168.1.52 (192.168.1.52): 56 data bytes
          64 bytes from 192.168.1.52: icmp_seq=0 ttl=64 time=0.117 ms
          64 bytes from 192.168.1.52: icmp_seq=1 ttl=64 time=0.163 ms
          64 bytes from 192.168.1.52: icmp_seq=2 ttl=64 time=0.117 ms
          64 bytes from 192.168.1.52: icmp_seq=3 ttl=64 time=0.102 ms
          64 bytes from 192.168.1.52: icmp_seq=4 ttl=64 time=0.163 ms
          ^C--- 192.168.1.52 ping statistics ---
          5 packets transmitted, 5 packets received, 0% packet loss
          round-trip min/avg/max/stddev = 0.102/0.132/0.163/0.026 ms

**Comment by maxdd** [comment]
could be related to #107 ?

**Comment by rozetko** [comment]
Hey @maxdd

Yeah, the issue you mention is related to #107 
The reason is that the server can't connect to the DB because of a network-related error (`tcp connect error: Connection refused` in your case)
So I'm guessing your Influx doesn't listen to `http://192.168.1.52:8086`, maybe it only listens to localhost or docker-compose-network

Can I ask you to check with `curl` or `telnet` if `http://192.168.1.52:8086` is accessible from inside the hastic container?
Also, it'd be nice if you send the whole `docker-compose.yml` you're using so that I can try to run it locally

P.S. do you use the same `http://192.168.1.52:8086` URL in Grafana to connect to Influx?

**Comment by maxdd** [comment]
Hello @rozetko 
thank you for the feedback.
My influx docker is accessible from everywhere in the network as well as from all my VPNs Site (just to show you that it is not confined in the host machine or in the specific stack network).

This is the grafana datasource to give you an example (which is on a different docker on the same stack)
![image](https://user-images.githubusercontent.com/6155973/190630290-06a062de-b2fa-498b-8fc3-71a26fa12e94.png)

        root@ubuntu:/# curl http://192.168.1.52:8086
        <!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="
        description" content="InfluxDB is a time series platform, purpose-built by InfluxData for storing metrics and events, provides real-time visibility into stacks, sensors, and systems."><title>InfluxDB</title><base href="/"><link rel="shortcut icon" href="/favicon.ico"></head><body><div id="react-root" data-basepath=""></div><script src="/cc16dd8913.js"></script></body></html>

**Comment by maxdd** [comment]
Hello @rozetko 
thank you for the support.
I hope you are still planning to release a sort of community version at least.
In any case i did the change but i get

        analytic status: { "Error": "Cant' extract metric: no measurement at position 8" }

my query is as follow

        HASTIC_INFLUX__QUERY: "from(bucket: \"eMgr\")\n  |> $$range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sdm230\")\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_P\")"

**Comment by rozetko** [comment]
@maxdd 

We don't have enough time now so it might take a few weeks to fix this one. Also, we're concerned that you might have more errors until you get results.

It'll really help debugging and speed up the development if you share your dataset with us. You can replace confidential data with something and send it to rozetko@corpglory.com

**Comment by maxdd** [comment]
Hello Rozetko,
here is the dataset, you can load it directly from influxdb web ui.
Let me know if I can help somehow.
I'm really eager to play a bit with hastic.

Regards.

Il giorno lun 19 set 2022 alle ore 18:53 rozetko ***@***.***>
ha scritto:
