### ISSUE TITLE
Analytic is stuck at Learning

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic#42]
I've changed the Seasonality value from 7220 to 722 and now I can't do anything, analytics always showing the Learning status

Maybe we can display logs somewhere so that a user have better understanding of what's going on

![image](https://user-images.githubusercontent.com/1989898/144051318-1e27582c-a3eb-4706-ae25-cef87c12a7ab.png)

**Comment by rozetko** [comment]
found an error in logs:

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: to short timeserie to learn from', src/services/analytic_service/analytic_unit/anomaly_analytic_unit.rs:184:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: timeserie to learn from should be 3 * sasonality', src/services/analytic_service/analytic_unit/anomaly_analytic_unit.rs:184:26
```

**Comment by rozetko** [comment]
btw, looks like analytic stucks at Learning on any error

so, I guess, this issue is about displaying errors in UI now :)
